"""HTML reporter — generates a self-contained HTML report."""

from __future__ import annotations

from pathlib import Path

from ..models import AuditResult


def render_html(result: AuditResult) -> str:
    """Generate a self-contained HTML report."""
    findings_html = ""
    for f in result.findings:
        sev_class = f.severity.name.lower()
        loc = f.file or ""
        if f.line:
            loc += f":{f.line}"
        findings_html += f"""
        <tr class="finding-{sev_class}">
            <td class="sev">{f.severity.name}</td>
            <td class="cat">{f.category}</td>
            <td class="loc">{loc}</td>
            <td>{f.title}</td>
            <td class="rec">{f.recommendation}</td>
        </tr>"""

    scores_html = ""
    for cat, score in result.scores.items():
        color = "#4caf50" if score >= 80 else "#ff9800" if score >= 60 else "#f44336"
        scores_html += f"""
        <div class="score-row">
            <span class="score-label">{cat}</span>
            <div class="score-bar-bg">
                <div class="score-bar" style="width:{score}%;background:{color}"></div>
            </div>
            <span class="score-val">{score:.0f}</span>
        </div>"""

    overall_color = "#4caf50" if result.overall_score >= 80 else "#ff9800" if result.overall_score >= 60 else "#f44336"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>KodeAudit Report — {Path(result.project.root).name}</title>
<style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
           max-width: 960px; margin: 40px auto; padding: 0 20px; color: #333; }}
    h1 {{ font-size: 24px; border-bottom: 2px solid #ddd; padding-bottom: 8px; }}
    h2 {{ font-size: 18px; margin-top: 32px; }}
    .overall {{ font-size: 48px; font-weight: bold; color: {overall_color}; }}
    .score-row {{ display: flex; align-items: center; margin: 8px 0; }}
    .score-label {{ width: 120px; }}
    .score-bar-bg {{ flex: 1; height: 20px; background: #eee; border-radius: 4px; margin: 0 12px; }}
    .score-bar {{ height: 100%; border-radius: 4px; transition: width 0.3s; }}
    .score-val {{ width: 40px; text-align: right; font-weight: bold; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 16px; }}
    th, td {{ text-align: left; padding: 8px 12px; border-bottom: 1px solid #eee; }}
    th {{ background: #f5f5f5; }}
    .sev {{ font-weight: bold; white-space: nowrap; }}
    .rec {{ color: #666; font-style: italic; }}
    .finding-critical, .finding-high {{ background: #fff3f3; }}
    .finding-medium {{ background: #fffde7; }}
    .finding-low, .finding-info {{ background: #f5f9ff; }}
    .meta {{ color: #666; font-size: 14px; }}
</style>
</head>
<body>
<h1>KodeAudit Report</h1>
<p class="meta">Project: {result.project.root}</p>
<p class="meta">Languages: {', '.join(f'{l} {p}%' for l, p in list(result.project.languages.items())[:5])}</p>

<h2>Project Health</h2>
<div class="overall">{result.overall_score:.0f}/100</div>
{scores_html}

<h2>Findings ({len(result.findings)})</h2>
<table>
<tr><th>Severity</th><th>Category</th><th>Location</th><th>Finding</th><th>Recommendation</th></tr>
{findings_html}
</table>

<h2>Top Recommendations</h2>
<ol>
{''.join(f'<li>{r}</li>' for r in result.recommendations)}
</ol>

<p class="meta">Generated by KodeAudit v0.1.0</p>
</body>
</html>"""
